### PR TITLE
Added notes to products overview

### PR DESCRIPTION
**Pull request by anchit-chandran**
- added bit to overview
-

### CODE REVIEW

**Comment by pacharanero** [comment]
Thanks! nice work

**Comment by pacharanero** [comment]
Test at https://anchit-chandran.github.io/digital-growth-charts-documentation/

**Review by eatyourpeas — CHANGES_REQUESTED** [review]
Actually this is now a little out of date. In the API server Flask and Marshmallow have both been deprecated so that section can be removed and instead needs a section of FastAPI.

**Comment by pacharanero** [comment]
I've merged it in for now as it's got good content in the Overview.
I will fix the details on Flask etc in due course

**Pull request merged**
