### PR TITLE
Tidy up doc

### PR DESCRIPTION
**Pull request by a-wei-william**
Tidy up pages under "Products"

### CODE REVIEW

**Comment by a-wei-william** [comment]
tidy up the reactive native client page

- removed the broken image link
- change the GitHub link to GitHub Repository
- commented out the website icon (not sure what it was meant to link to)

**Comment by a-wei-william** [comment]
tidy up command-line-client [529fa08](https://github.com/rcpch/digital-growth-charts-documentation/pull/30/commits/529fa085b6c4b7d1bcf0101a6ee828c59b23e6ee) 

- change the commands to heading with code block(although its not very obvious that its a code block when its also heading. i wasn't sure how to make a code block for the command that has larger font size so it looks like a heading)
- change heading three to normal bold text so table of content looks cleaner [4f0cf77](https://github.com/rcpch/digital-growth-charts-documentation/pull/30/commits/4f0cf779c2d1a8fb82c1221d87e5684c5443e841)

**Comment by pacharanero** [comment]
Hi @a-wei-0513 thanks for the PR! Let's get you set up with a test deployment that we can look at:

If you go into your GitHub Actions settings you should be able to enable the publish action, this is included in your fork of our repo, but GitHub disables Actions in forks for security reasons, you have to enable them manually. The Action has 2 parts: the second one (publish to Azure) will fail, but it won't matter because the first part is all you need for this.

Then go into GitHub Pages settings and enable the publication of the gh-pages branch of your fork, this will give us a nice page we can test your PR our before we merge, it would be at something like: https://a-wei-0513.github.io/digital-growth-charts-documentation/

**Comment by a-wei-william** [comment]
Hi @pacharanero I've done it

**Comment by pacharanero** [comment]
Looks good to me @a-wei-0513 - I would like @eatyourpeas to have a look as he wrote the CLI and the documentation for it
Simon you can see the PR edits deployed at https://a-wei-0513.github.io/digital-growth-charts-documentation/products/command-line-client/

**Comment by a-wei-william** [comment]
fixes #31

**Comment by pacharanero** [comment]
@a-wei-0513 I have been having a look through this PR. There's a lot here so it may take a few more days to be ready to merge it.

I may actually merge it into a different branch on the `rcpch` organisation account so that we can make any final tweaks.

Small point of feedback about PRs is that when there is a lot of changes, can be better to do each 'functionally separate' atomic change in its own branch and make separate PRs for each.

Going forward we are trying to use a workflow that is

Single Issue => Feature branch to fix that issue => PR for that issue => Merge => Close issue

**Review by pacharanero — DISMISSED** [review]

**Comment by pacharanero** [comment]
I've had a read through all of it now, and it's great stuff. Thanks so much for this.

The only modification I would like to request would be in the Products>CLI tools bit, could we use Markdown headings even for the  Arguments/Options/Example bits? You've switched out H3s for bold text but I think for almost everything we are trying to stick to using headings as they are linkable. Could we switch these back and push the changes here and I'll merge.

**Comment by a-wei-william** [comment]
fixed #26 ?

**Comment by pacharanero** [comment]
@a-wei-0513 merged and I've added you to the Contributor list https://growth.rcpch.ac.uk/about/acknowledgements/

**Comment by pacharanero** [comment]
When we get you working on the Python code we can add that as well as documentation work!

**Comment by a-wei-william** [comment]
@pacharanero Great! Thank you 😁

**Pull request merged**
